Automobile/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Automobile.Models
{
    public class Auto
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Ko je {0}?")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Minimum number of characters is 2, and maximum is 50")]
        [Display(Name = "Proizvodjac")]
        public string Manufacturer { get; set; }

        [Required(ErrorMessage = "Unesi naziv {0}a")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Minimum number of characters is 2, and maximum is 50")]
        [Display(Name = "Model")]
        public string Model { get; set; }

        [Required(ErrorMessage = "This is required field!")]
        [Range(1885, 2018, ErrorMessage = "{0} proizvodnje mora biti izmedju 1885 i 2018")]
        [Display(Name = "Godina")]
        public int Year { get; set; }

        [Required(ErrorMessage = "This is required field!")]
        [Range(500, 10000, ErrorMessage = "Automobil mora da ima izmedju 500 i 10000 {0}a")]
        [Display(Name = "Kubik")]
        public int Cubic { get; set; }

        [Required(ErrorMessage = "{0} je obavezno polje")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Minimum number of characters is 2, and maximum is 50")]
        [Display(Name = "Boja")]
        public string Color { get; set; }

        public Motor Motor { get; set; }

        public Auto()
        {
            this.Motor = new Motor();
        }

        public Auto(int id, string manufacturer, string model, int year, int cubic, string colour) : this()
        {
            this.Id = id;
            this.Manufacturer = manufacturer;
            this.Model = model;
            this.Year = year;
            this.Cubic = cubic;
            this.Color = colour;
        }
    }
}

Automobile/Models/Motor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Automobile.Models
{
    public class Motor
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Unesi {0} care molim te :)")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Minimum number of characters is 2, and maximum is 50")]
        [Display(Name = "Naziv")]
        public string Name { get; set; }

        public List<Auto> Autos { get; set; }

        public Motor()
        {
            this.Autos = new List<Auto>();
        }

        public Motor(string name) : this()
        {
            this.Name = name;
        }

        public Motor(int id, string name) : this(name)
        {
            this.Id = id;
        }
    }
}

Automobile/ViewModels/AutoMotorsViewModel.cs
using Automobile.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Automobile.ViewModels
{
    public class AutoMotorsViewModel
    {
        public Auto Auto { get; set; }
        public List<Motor> Motors { get; set; }
        public int SelectedMotorId { get; set; }
    }
}

Automobile/Controllers/AutosController.cs
using Automobile.Interfaces;
using Automobile.Models;
using Automobile.Repository;
using Automobile.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Automobile.Controllers
{
    public class AutosController : Controller
    {
        private IAutoRepository aRepository = new AutoRepository();
        private IMotorRepository mRepository = new MotorRepository();

        // GET: Autos
        public ActionResult Index()
        {
            var autos = aRepository.GetAll();
            foreach (var item in autos)
            {
                var res = mRepository.GetById(item.Motor.Id);
                item.Motor = res;
            }
            return View(autos);
        }

        // GET: Auto
        public ActionResult Create()
        {
            var motors = mRepository.GetAll();
            AutoMotorsViewModel amvm = new AutoMotorsViewModel();
            amvm.Motors = motors;
            return View(amvm);
        }

        // POST: Auto
        [HttpPost]
        public ActionResult Create(AutoMotorsViewModel amvm)
        {
            if (ModelState.IsValid)
            {
                amvm.Auto.Motor.Id = amvm.SelectedMotorId;
                var res = aRepository.Create(amvm.Auto);
                if (res)
                {
                    return RedirectToAction("Index");
                }
            }

            var motors = mRepository.GetAll();
            amvm.Motors = motors;

            return View(amvm);
        }

        // GET: Auto
        public ActionResult Edit(int id)
        {
            AutoMotorsViewModel amvm = new AutoMotorsViewModel();
            amvm.Auto = aRepository.GetById(id);
            amvm.Motors = mRepository.GetAll();
            amvm.SelectedMotorId = amvm.Auto.Motor.Id;
            return View(amvm);
        }

        // GET: Auto
        [HttpPost]
        public ActionResult Edit(AutoMotorsViewModel amvm)
        {
            if (ModelState.IsValid)
            {
                amvm.Auto.Motor.Id = amvm.SelectedMotorId;
                var res = aRepository.Update(amvm.Auto);
                if (res)
                {
                    return RedirectToAction("Index");
                }
            }
            var motors = mRepository.GetAll();
            amvm.Motors = motors;
            return View(amvm);
        }

        // GET: Auto
        public ActionResult Delete(int id)
        {
            var res = aRepository.Delete(id);
            if (res)
            {
                return RedirectToAction("Index");
            }
            return Content("Greska prilikom brisanja");
        }
    }
}

Automobile/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Automobile.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Automobile/Controllers/MotorsController.cs
using Automobile.Interfaces;
using Automobile.Models;
using Automobile.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Automobile.Controllers
{
    public class MotorsController : Controller
    {
        private IMotorRepository mRepository = new MotorRepository();

        // GET: Motors
        public ActionResult Index()
        {
            var res = mRepository.GetAll();
            return View(res);
        }

        // GET: Motor
        public ActionResult Create()
        { 
            return View();
        }

        // POST: Motor
        [HttpPost]
        public ActionResult Create(Motor motor)
        {
            if (ModelState.IsValid)
            {
                var res = mRepository.Create(motor);
                return RedirectToAction("Index");
            }
            return View(motor);
        }

        // GET: Motor
        public ActionResult Edit(int id)
        {
            var res = mRepository.GetById(id);
            return View(res);
        }

        // GET: Motor
        [HttpPost]
        public ActionResult Edit(Motor motor)
        {
            if (ModelState.IsValid)
            {
                var res = mRepository.Update(motor);
                return RedirectToAction("Index");
            }
            return View(motor);
        }

        // GET: Motor
        public ActionResult Delete(int id)
        {
            var res = mRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Automobile/Views/Autos/Create.cshtml
@model Automobile.ViewModels.AutoMotorsViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<hr />
@using (Html.BeginForm("Create", "Autos", FormMethod.Post, new { onsubmit = "return validateFormAuto(this)" }))
{
<div class="form-horizontal">
    @*<div class="form-group">
        <div class="col-md-10">
            @Html.ValidationSummary()
        </div>
    </div>*@
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Manufacturer)
            @Html.EditorFor(a => a.Auto.Manufacturer)
            @Html.ValidationMessageFor(a => a.Auto.Manufacturer, "", new { @class = "text-danger", id = "manufacturer1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Model)
            @Html.EditorFor(a => a.Auto.Model)
            @Html.ValidationMessageFor(a => a.Auto.Model, "", new { @class = "text-danger", id = "model1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Year)
            @Html.EditorFor(a => a.Auto.Year)
            @Html.ValidationMessageFor(a => a.Auto.Year, "", new { @class = "text-danger", id = "year1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Cubic)
            @Html.EditorFor(a => a.Auto.Cubic)
            @Html.ValidationMessageFor(a => a.Auto.Cubic, "", new { @class = "text-danger", id = "cubic1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Color)
            @Html.EditorFor(a => a.Auto.Color)
            @Html.ValidationMessageFor(a => a.Auto.Color, "", new { @class = "text-danger", id = "color1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Motors.FirstOrDefault().Name)
            @Html.DropDownListFor(a => a.SelectedMotorId,
                    new SelectList(Model.Motors, "Id", "Name"))
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>

Automobile/Views/Autos/Edit.cshtml
@model Automobile.ViewModels.AutoMotorsViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Autos", FormMethod.Post, new { onsubmit = "return validateFormAuto(this)" }))
{
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Manufacturer)
            @Html.EditorFor(a => a.Auto.Manufacturer)
            @Html.ValidationMessageFor(a => a.Auto.Manufacturer, "", new { @class = "text-danger", id = "manufacturer1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Model)
            @Html.EditorFor(a => a.Auto.Model)
            @Html.ValidationMessageFor(a => a.Auto.Model, "", new { @class = "text-danger", id = "model1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Year)
            @Html.EditorFor(a => a.Auto.Year)
            @Html.ValidationMessageFor(a => a.Auto.Year, "", new { @class = "text-danger", id = "year1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Cubic)
            @Html.EditorFor(a => a.Auto.Cubic)
            @Html.ValidationMessageFor(a => a.Auto.Cubic, "", new { @class = "text-danger", id = "cubic1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Auto.Color)
            @Html.EditorFor(a => a.Auto.Color)
            @Html.ValidationMessageFor(a => a.Auto.Color, "", new { @class = "text-danger", id = "color1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(a => a.Motors.FirstOrDefault().Name)
            @Html.DropDownListFor(a => a.SelectedMotorId,
                new SelectList(Model.Motors, "Id", "Name", Model.SelectedMotorId))
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            @Html.HiddenFor(a => a.Auto.Id)
            <input type="submit" value="Edit" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>

Automobile/Views/Autos/Index.cshtml
@model IEnumerable<Automobile.Models.Auto>

@{
    ViewBag.Title = "Index";
}

<h2>Autos</h2>
<hr />
<table class="table table-striped" border="1">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Manufacturer</th>
            <th scope="col">Model</th>
            <th scope="col">Year</th>
            <th scope="col">Cubic</th>
            <th scope="col">Color</th>
            <th scope="col">Motor</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {

        <tr>
            <td>@Html.DisplayFor(Model => m.Manufacturer)</td>
            <td>@Html.DisplayFor(Model => m.Model)</td>
            <td>@Html.DisplayFor(Model => m.Year)</td>
            <td>@Html.DisplayFor(Model => m.Cubic)</td>
            <td>@Html.DisplayFor(Model => m.Color)</td>
            <td>@Html.DisplayFor(Model => m.Motor.Name)</td>
            <td>@Html.ActionLink("edit", "Edit", "Autos", new { id = m.Id }, null)</td>
            <td>@Html.ActionLink("delete", "Delete", new { id = m.Id })</td>
            <td>@Html.ActionLink("new", "Create")</td>
        </tr>
        }
    </tbody>
    </table>
<hr />

Automobile/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Automobile/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Automobile/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Automobile/Views/Motors/Create.cshtml
@model Automobile.Models.Motor

@{
    ViewBag.Title = "Create";
}

<h2>Create motor</h2>
<hr />
@using (Html.BeginForm("Create", "Motors", FormMethod.Post, new { onsubmit = "return validateFormMotor(this)" }))
{
<div class="form-horizontal">
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(m => m.Name)
            @Html.EditorFor(m => m.Name)
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger", id = "name1" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Back", "Index")
</div>

Automobile/Views/Motors/Edit.cshtml
@model Automobile.Models.Motor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<hr />
@using (Html.BeginForm("Edit", "Motors", FormMethod.Post, new { onsubmit = "return validateFormMotor(this)" }))
    {
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(m => m.Name)
                @Html.EditorFor(m => m.Name)
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger", id = "name1" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Edit" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    <div>
        @Html.ActionLink("Back", "Index")
    </div>

Automobile/Views/Motors/Index.cshtml
@model IEnumerable<Automobile.Models.Motor>

@{
    ViewBag.Title = "Index";
}

<h2>Motors</h2>
<hr/>
<table class="table table-striped" border="1">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
        <tr>
            <td>@Html.DisplayFor(Model => m.Name)</td>
            <td>@Html.ActionLink("edit", "Edit", "Motors", new { id = m.Id }, null)</td>
            <td>@Html.ActionLink("delete", "Delete", new { id = m.Id })</td>
            <td>@Html.ActionLink("new", "Create")</td>
        </tr>
        }
    </tbody>
</table>

Automobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/AutomobileScript")
</head>
<body>
    <div class="navbar navbar-dark navbar-fixed-top bg-dark">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Automobiles", "Index", "Autos", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Motors", "Index", "Motors", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>